name: Deploy website
on:
  push:
    branches:
      - events
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: echo something
        run: echo "something"
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-files
          path: |
            src/test
            package.json
      - name: upload artifacts 2
        uses: actions/upload-artifact@v3
        with:
          name: second-arti
          path: package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
      - name: download artifact
        uses: actions/download-artifact@v3
        with: 
          name: second-arti
      - name: output content
        run: ls
