name: issues
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: iisue type
        run: echo "Issue is ${{ github.event.issue.title }}"